site_name: John Doe Shop
copyright: John Doe Shop 2015
pages:
  - Home: index.md
  - Liquid:
    - 'Introduction': 'liquid/introduction.md'
    - Objects:
      - 'Global Scope':
        - 'Shop': 'liquid/shop.md'
      - 'Local Scope':
        - 'Category': 'liquid/category.md'
    - 'Machine Learning': 'liquid/machine-learning.md'
  - 'JSON Endpoints':
    - 'Cart' : 'endpoints/cart.md'
theme: readthedocs
